version: "3.8"

services:
  notmuch: 
    image: gkappler/notmuch-elmail #:1.2.0
    container_name: notmuch-elmail
    build: .
    ports:
      - "9999:9999"  # Expose API port
    env_file:
      - ./.env
    volumes: # Persist data in seperate volume
      - ./home:/home
          
